# Generated by Django 5.1.2 on 2024-11-04 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_remove_incident_assigned_responder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='status',
        ),
    ]
