# Generated by Django 5.1.2 on 2024-11-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_remove_incident_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='latitude',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='longitude',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
