# Generated by Django 5.1.2 on 2024-11-05 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0005_alter_incident_latitude_alter_incident_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='phone_no',
            field=models.CharField(default='null', max_length=15),
        ),
        migrations.AddField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('reported', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='reported', max_length=20),
        ),
    ]
