# Generated by Django 5.1.2 on 2024-11-09 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Shelters',
            fields=[
                ('camp_id', models.AutoField(primary_key=True, serialize=False)),
                ('camp_address', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField()),
                ('contact', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('license_plate', models.CharField(max_length=15)),
                ('vehicle_type', models.CharField(choices=[('bus', 'Bus'), ('truck', 'Truck'), ('van', 'Van'), ('car', 'Car')], max_length=20)),
                ('current_status', models.CharField(choices=[('available', 'Available'), ('in use', 'In Use'), ('maintenance', 'Under Maintenance')], max_length=20)),
                ('location', models.CharField(default='xxx', max_length=100)),
                ('contact_info', models.CharField(max_length=100)),
            ],
        ),
    ]
