# Generated by Django 5.1.2 on 2024-11-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_transportrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportrequest',
            name='user_alert',
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='phone_no',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='transportrequest',
            name='request_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accept', 'Accept'), ('completed', 'Completed'), ('cancel', 'Cancel')], default='pending', max_length=20),
        ),
    ]
