# Generated by Django 5.1.2 on 2024-11-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_transportrequest_user_alert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportrequest',
            name='phone_no',
            field=models.CharField(max_length=20),
        ),
    ]
