# Generated by Django 5.1.2 on 2024-11-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_transportrequest_phone_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportation',
            name='location',
        ),
        migrations.RemoveField(
            model_name='transportrequest',
            name='user',
        ),
        migrations.AddField(
            model_name='transportation',
            name='latitude',
            field=models.FloatField(default=8.5),
        ),
        migrations.AddField(
            model_name='transportation',
            name='longitude',
            field=models.FloatField(default=76.8),
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='username',
            field=models.CharField(default=8, max_length=20),
            preserve_default=False,
        ),
    ]
