# Generated by Django 5.1.2 on 2024-11-11 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_transportation_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportrequest',
            name='username',
        ),
    ]
