# Generated by Django 5.1.2 on 2024-11-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('victim', 'Victim'), ('responder', 'Responder'), ('admin', 'Admin'), ('transport', 'Transport')], default='victim', max_length=20),
        ),
    ]
